# Generated by Django 3.2.16 on 2023-03-30 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configure', '0007_auto_20230226_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(related_name='questions', to='configure.Tags'),
        ),
    ]
