# Generated by Django 4.1.6 on 2023-04-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configure', '0008_alter_question_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=511, unique=True),
        ),
    ]
