# Generated by Django 3.2.16 on 2023-04-19 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configure', '0009_alter_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='subcategory',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='configure.subcategory'),
            preserve_default=False,
        ),
    ]
