# Generated by Django 3.2.16 on 2023-04-20 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configure', '0009_alter_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='configure.subcategory'),
        ),
    ]
