# Generated by Django 3.2.16 on 2024-10-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configure', '0010_question_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='eras_list',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
