# Generated by Django 3.2.16 on 2023-04-20 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configure', '0011_alter_question_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='subcategory',
        ),
    ]
